import { Request, Response } from "express";

export const handleChatbotQuery = async (req: Request, res: Response) => {
  const { message, history } = req.body;
  const apiKey = process.env.OPENROUTER_API_KEY;

  if (!apiKey || apiKey === "your_openrouter_api_key_here") {
    console.error("OpenRouter API key is missing or is the placeholder");
    return res.status(500).json({ error: "Chatbot is currently offline (API key not configured)" });
  }

  if (!message) {
    return res.status(400).json({ error: "Message is required" });
  }

  console.log(`Chatbot request: "${message}" (History: ${history?.length || 0} messages)`);

  try {
    const systemPrompt = `You are Hope, an AI for the "Drop of Hope" blood donation platform.
ONLY answer questions about: donor eligibility, donation process, health prep, and rewards.
STRICT RULES:
1. Decline unrelated topics (coding, general knowledge, etc.) and remind user of your role.
2. Tone: Encouraging, professional, concise.
3. If medical uncertainty arises, advise consulting center professionals.
Platform Data: Whole blood (100 pts), Platelets (150 pts). Age 17+, Weight 110lbs+. Wait 56 days between whole blood donations.`;

    const response = await fetch("https://openrouter.ai/api/v1/chat/completions", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${apiKey}`,
        "HTTP-Referer": "https://drop-of-hope.vercel.app", // Optional, for OpenRouter rankings
        "X-Title": "Drop of Hope Chatbot", // Optional, for OpenRouter rankings
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        "model": "poolside/laguna-xs.2:free",
        "messages": [
          { "role": "system", "content": systemPrompt },
          ...(history || []).map((h: any) => ({
            role: h.type === "user" ? "user" : "assistant",
            content: h.content
          })).filter((h: any) => h.content && typeof h.content === 'string'),
          { "role": "user", "content": message }
        ]
      })
    }); 

    const data = await response.json();

    if (!response.ok) {
      console.error("OpenRouter API error details:", JSON.stringify(data, null, 2));
      const errorMsg = data.error?.message || data.error?.metadata?.raw || "Failed to fetch from AI provider";
      return res.status(response.status).json({ error: errorMsg });
    }

    if (!data.choices || data.choices.length === 0) {
      console.error("OpenRouter returned no choices:", data);
      return res.status(500).json({ error: "No response generated by AI" });
    }

    const aiMessage = data.choices[0].message.content;
    res.json({ content: aiMessage });
  } catch (error: any) {
    console.error("Chatbot error:", error);
    res.status(500).json({ error: error.message || "Failed to generate response" });
  }
};
